// Mocks generated by Mockito 5.4.4 from annotations
// in telegrammy/test/cores/services/mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dio/dio.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:telegrammy/cores/services/profile_api_service.dart' as _i8;
import 'package:telegrammy/cores/services/token_storage_service.dart' as _i12;
import 'package:telegrammy/features/profile/data/models/blocked_user_model.dart'
    as _i4;
import 'package:telegrammy/features/profile/data/models/contacts_toblock_model.dart'
    as _i5;
import 'package:telegrammy/features/profile/data/models/profile_info_model.dart'
    as _i7;
import 'package:telegrammy/features/profile/data/models/profile_visibility_model.dart'
    as _i10;
import 'package:telegrammy/features/profile/data/models/settings_user_model.dart'
    as _i3;
import 'package:telegrammy/features/profile/data/models/stories_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserPrivacySettingsResponse_1 extends _i1.SmartFake
    implements _i3.UserPrivacySettingsResponse {
  _FakeUserPrivacySettingsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockedUsersResponse_2 extends _i1.SmartFake
    implements _i4.BlockedUsersResponse {
  _FakeBlockedUsersResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContactsResponse_3 extends _i1.SmartFake
    implements _i5.ContactsResponse {
  _FakeContactsResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStoryResponse_4 extends _i1.SmartFake implements _i6.StoryResponse {
  _FakeStoryResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileInfoResponse_5 extends _i1.SmartFake
    implements _i7.ProfileInfoResponse {
  _FakeProfileInfoResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfilePictureResponse_6 extends _i1.SmartFake
    implements _i7.ProfilePictureResponse {
  _FakeProfilePictureResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiService extends _i1.Mock implements _i8.ProfileApiService {
  MockProfileApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i9.Future<_i3.UserPrivacySettingsResponse> getUserSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSettings,
          [],
        ),
        returnValue: _i9.Future<_i3.UserPrivacySettingsResponse>.value(
            _FakeUserPrivacySettingsResponse_1(
          this,
          Invocation.method(
            #getUserSettings,
            [],
          ),
        )),
      ) as _i9.Future<_i3.UserPrivacySettingsResponse>);

  @override
  _i9.Future<void> updateProfileVisibility(
          _i10.ProfileVisibility? profileVisibility) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileVisibility,
          [profileVisibility],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i4.BlockedUsersResponse> getBlockedUsers() => (super.noSuchMethod(
        Invocation.method(
          #getBlockedUsers,
          [],
        ),
        returnValue: _i9.Future<_i4.BlockedUsersResponse>.value(
            _FakeBlockedUsersResponse_2(
          this,
          Invocation.method(
            #getBlockedUsers,
            [],
          ),
        )),
      ) as _i9.Future<_i4.BlockedUsersResponse>);

  @override
  _i9.Future<_i5.ContactsResponse> getContacts() => (super.noSuchMethod(
        Invocation.method(
          #getContacts,
          [],
        ),
        returnValue:
            _i9.Future<_i5.ContactsResponse>.value(_FakeContactsResponse_3(
          this,
          Invocation.method(
            #getContacts,
            [],
          ),
        )),
      ) as _i9.Future<_i5.ContactsResponse>);

  @override
  _i9.Future<void> updateBlockingStatus(
    String? action,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBlockingStatus,
          [
            action,
            userId,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateReadReceiptsStatus(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReadReceiptsStatus,
          [isEnabled],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i6.StoryResponse> getUserStories() => (super.noSuchMethod(
        Invocation.method(
          #getUserStories,
          [],
        ),
        returnValue: _i9.Future<_i6.StoryResponse>.value(_FakeStoryResponse_4(
          this,
          Invocation.method(
            #getUserStories,
            [],
          ),
        )),
      ) as _i9.Future<_i6.StoryResponse>);

  @override
  _i9.Future<void> createStory(_i6.StoryCreation? storyCreation) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStory,
          [storyCreation],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteStory(String? storyId) => (super.noSuchMethod(
        Invocation.method(
          #deleteStory,
          [storyId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i7.ProfileInfoResponse> getProfileInfo() => (super.noSuchMethod(
        Invocation.method(
          #getProfileInfo,
          [],
        ),
        returnValue: _i9.Future<_i7.ProfileInfoResponse>.value(
            _FakeProfileInfoResponse_5(
          this,
          Invocation.method(
            #getProfileInfo,
            [],
          ),
        )),
      ) as _i9.Future<_i7.ProfileInfoResponse>);

  @override
  _i9.Future<void> updateProfileInfo(_i7.ProfileInfo? profileInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileInfo,
          [profileInfo],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserActivityStatus(String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserActivityStatus,
          [status],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #updateUserEmail,
          [email],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateUsername(String? username) => (super.noSuchMethod(
        Invocation.method(
          #updateUsername,
          [username],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserPhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPhoneNumber,
          [phoneNumber],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i7.ProfilePictureResponse> updateProfilePic(
          _i11.XFile? pickedFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfilePic,
          [pickedFile],
        ),
        returnValue: _i9.Future<_i7.ProfilePictureResponse>.value(
            _FakeProfilePictureResponse_6(
          this,
          Invocation.method(
            #updateProfilePic,
            [pickedFile],
          ),
        )),
      ) as _i9.Future<_i7.ProfilePictureResponse>);

  @override
  _i9.Future<void> deleteProfilePicture() => (super.noSuchMethod(
        Invocation.method(
          #deleteProfilePicture,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [TokenStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageService extends _i1.Mock
    implements _i12.TokenStorageService {
  MockTokenStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> saveEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #saveEmail,
          [email],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<String?> getEmail() => (super.noSuchMethod(
        Invocation.method(
          #getEmail,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteEmail() => (super.noSuchMethod(
        Invocation.method(
          #deleteEmail,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
