// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0zLXiBij35Gc7XAj7pTWqFZNQldpIJc8',
    appId: '1:49270575708:web:6347dae0eed5f547510c99',
    messagingSenderId: '49270575708',
    projectId: 'telegrammy-sw',
    authDomain: 'telegrammy-sw.firebaseapp.com',
    storageBucket: 'telegrammy-sw.firebasestorage.app',
    measurementId: 'G-YK1QJ7MXT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgVr11HDnmui41bS8AzdxlyRrV-GrOSQU',
    appId: '1:49270575708:android:ddac98229390f959510c99',
    messagingSenderId: '49270575708',
    projectId: 'telegrammy-sw',
    storageBucket: 'telegrammy-sw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaAZOcuHA24DS7sC6clvzlEjoFl8Y2byc',
    appId: '1:49270575708:ios:0ddab49c84455ed5510c99',
    messagingSenderId: '49270575708',
    projectId: 'telegrammy-sw',
    storageBucket: 'telegrammy-sw.firebasestorage.app',
    iosBundleId: 'com.example.telegrammy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaAZOcuHA24DS7sC6clvzlEjoFl8Y2byc',
    appId: '1:49270575708:ios:0ddab49c84455ed5510c99',
    messagingSenderId: '49270575708',
    projectId: 'telegrammy-sw',
    storageBucket: 'telegrammy-sw.firebasestorage.app',
    iosBundleId: 'com.example.telegrammy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0zLXiBij35Gc7XAj7pTWqFZNQldpIJc8',
    appId: '1:49270575708:web:5e38f65c52ef6b6b510c99',
    messagingSenderId: '49270575708',
    projectId: 'telegrammy-sw',
    authDomain: 'telegrammy-sw.firebaseapp.com',
    storageBucket: 'telegrammy-sw.firebasestorage.app',
    measurementId: 'G-XZGGT670WG',
  );

}