// Mocks generated by Mockito 5.4.4 from annotations
// in telegrammy/test/features/auth/presentaions/widgets/profile_widgets_tests/widget_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bloc/bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:telegrammy/features/profile/data/repos/profile_repo.dart'
    as _i2;
import 'package:telegrammy/features/profile/presentation/view_models/blocked_users_cubit/blocked_users_cubit.dart'
    as _i4;
import 'package:telegrammy/features/profile/presentation/view_models/blocked_users_cubit/blocked_users_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileRepo_0 extends _i1.SmartFake implements _i2.ProfileRepo {
  _FakeProfileRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockedUsersState_1 extends _i1.SmartFake
    implements _i3.BlockedUsersState {
  _FakeBlockedUsersState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BlockedUsersCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockedUsersCubit extends _i1.Mock implements _i4.BlockedUsersCubit {
  MockBlockedUsersCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepo get profileRepo => (super.noSuchMethod(
        Invocation.getter(#profileRepo),
        returnValue: _FakeProfileRepo_0(
          this,
          Invocation.getter(#profileRepo),
        ),
      ) as _i2.ProfileRepo);

  @override
  _i3.BlockedUsersState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBlockedUsersState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.BlockedUsersState);

  @override
  _i5.Stream<_i3.BlockedUsersState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.BlockedUsersState>.empty(),
      ) as _i5.Stream<_i3.BlockedUsersState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadBlockedUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadBlockedUsers,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateBlockedUsers(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #updateBlockedUsers,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unblockUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void emit(_i3.BlockedUsersState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i6.Change<_i3.BlockedUsersState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
