services:
  backend:
    image: telegrammy/backend:messaging # telegrammy/backend:[module_name] (check with the backend repo)
    ports:
      - "8080:${PORT}"
    env_file:
      - .env
    networks:
      my-network:
networks:
  my-network:
